import 'package:flutter/cupertino.dart';

class PsValueHolder {
  PsValueHolder(
      {@required this.loginUserId,
      @required this.userIdToVerify,
      @required this.userNameToVerify,
      @required this.userEmailToVerify,
      @required this.userPasswordToVerify,
      @required this.deviceToken,
      @required this.notiSetting,
      @required this.overAllTaxLabel,
      @required this.overAllTaxValue,
      @required this.shippingTaxLabel,
      @required this.shippingTaxValue,
      @required this.appInfoVersionNo,
      @required this.appInfoForceUpdate,
      @required this.appInfoForceUpdateTitle,
      @required this.appInfoForceUpdateMsg,
      @required this.startDate,
      @required this.endDate,
      @required this.paypalEnabled,
      @required this.stripeEnabled,
      @required this.codEnabled,
      @required this.bankEnabled,
      @required this.publishKey});
  String loginUserId;
  String userIdToVerify;
  String userNameToVerify;
  String userEmailToVerify;
  String userPasswordToVerify;
  String deviceToken;
  bool notiSetting;
  String overAllTaxLabel;
  String overAllTaxValue;
  String shippingTaxLabel;
  String shippingTaxValue;
  String appInfoVersionNo;
  bool appInfoForceUpdate;
  String appInfoForceUpdateTitle;
  String appInfoForceUpdateMsg;
  String startDate;
  String endDate;
  String paypalEnabled;
  String stripeEnabled;
  String codEnabled;
  String bankEnabled;
  String publishKey;
}
